# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #Enter the name of the vagrant box here 
  config.vm.box = "zeab/ub-16.04-64x-plex"
  
  #UNCOMMENT To share folders from your host to your plex server
	#Windows To Linux
  #config.vm.synced_folder "C:/Some/Host/MediaFolder", "/SomeLocationInVM", type: "nfs"
	#Linux To Linux
  #config.vm.synced_folder "/Some/Host/MediaFolder", "/SomeLocationInVM"
  
  #UNCOMMENT to explose internal services out through portfowarding
  config.vm.network :forwarded_port, guest: 32400, host: 32400, id: "plex"
  
  #Virtualbox config
  config.vm.provider "virtualbox" do |vb|
	
	#Start vm with GUI
	vb.gui = false
	
	#SYSTEM SETTINGS
		#Modify Memory
	vb.customize ["modifyvm", :id, "--memory", 2048]
		#Modify CPU's
	vb.customize ["modifyvm", :id, "--cpus", 2]

	end
end