# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #Enter the name of the vagrant box here 
  config.vm.box = "zeab/ub-16.04-64x-elk"
  
  #Uncomment to mount another folder besides the defualt vagrant folder
  #config.vm.synced_folder "C:/Some/Host/Folder", "/Some/Location/In/VM"
  
  #Internal Services explosed by port forwarding
  config.vm.network :forwarded_port, guest: 8900, host: 8900, id: "Logstash-Http"
  config.vm.network :forwarded_port, guest: 5043, host: 5043, id: "Logstash-Beats"
  config.vm.network :forwarded_port, guest: 9200, host: 9200, id: "Elasticsearch"  
  config.vm.network :forwarded_port, guest: 5601, host: 5601, id: "Kibana"
  
  #Beggining of virtualbox config
  config.vm.provider "virtualbox" do |vb|
	
	#Option to start vm headless
	vb.gui = false
	
	#SYSTEM SETTINGS
	#Modify Memory
	vb.customize ["modifyvm", :id, "--memory", 4096]
	#Modify CPU's
	vb.customize ["modifyvm", :id, "--cpus", 4]
	
	end
end