# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #Enter the name of the vagrant box here 
  config.vm.box = "zeab/ub-16.04-64x-artifactory"
  
  #Uncomment to mount another folder besides the defualt vagrant folder
  #config.vm.synced_folder "C:/Some/Host/Folder", "/Some/Location/In/VM"
  
  #Uncomment to explose internal services out through portfowarding
  config.vm.network :forwarded_port, guest: 8081, host: 8081, id: "artifactory"
  
  #Beggining of virtualbox config
  config.vm.provider "virtualbox" do |vb|
	
	#Option to start vm headless
	vb.gui = false
	
	#SYSTEM SETTINGS
	#Modify Memory
	vb.customize ["modifyvm", :id, "--memory", 2048]
	#Modify CPU's
	vb.customize ["modifyvm", :id, "--cpus", 2]
	
	end
end